import { serializeVe, type VeEntry, type VeValue, veObject, veRaw } from "@omnimod/plugin-utils";

type TreeNode = { [key: string]: TreeNode | null };

/**
 * Render a `theme.css.ts` exposing a `createThemeContract` built from the union
 * of theme token paths accessed across the project (e.g. "colors.primary").
 * Leaves are `null` (the contract shape); the user assigns real values with
 * `createTheme(vars, { … })`.
 */
export function renderThemeFile(paths: Iterable<string>): string {
  return [
    'import { createThemeContract } from "@vanilla-extract/css";',
    "",
    "// Generated by omnimod from theme access in the migrated components.",
    "// Assign real values with: createTheme(vars, { …same shape… }).",
    `export const vars = createThemeContract(${serializeVe(buildContract([...paths]))});`,
    "",
  ].join("\n");
}

function buildContract(paths: string[]): VeValue {
  const root: TreeNode = {};
  for (const path of paths) {
    const keys = path.split(".").filter((key) => key.length > 0);
    if (keys.length === 0) continue;
    let node = root;
    for (let i = 0; i < keys.length - 1; i++) {
      const key = keys[i];
      if (node[key] === null || node[key] === undefined) node[key] = {};
      node = node[key] as TreeNode;
    }
    const leaf = keys[keys.length - 1];
    if (node[leaf] === undefined) node[leaf] = null;
  }
  return toVe(root);
}

function toVe(node: TreeNode | null): VeValue {
  if (node === null) return veRaw("null");
  const entries: VeEntry[] = Object.keys(node)
    .sort()
    .map((key) => ({ key, value: toVe(node[key]) }));
  return veObject(entries);
}
